# The URL the site will be built for
base_url = "https://endler.dev"

title = "Matthias Endler"
description = "Consultant at corrode.dev. Likes just-in-time compilers and hot chocolate"
author = "matthias@endler.dev (Matthias Endler)"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

minify_html = false

# Generate the JSON corpus consumed by tinysearch.
build_search_index = true

taxonomies = [{ name = "tags", feed = true, paginate_by = 10 }]

[search]
index_format = "fuse_json"

[markdown]
smart_punctuation = true
bottom_footnotes = true

[markdown.highlighting]
code = true
light_theme = "snazzy-light"
dark_theme = "dark-plus"
style = "class"
