SHELL := /bin/bash
TINYSEARCH_VERSION := 0.11.0

.PHONY: help
help: ## This help message
	@echo -e "$$(grep -hE '^\S+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##\s*/:/' -e 's/^\(.\+\):\(.*\)/\\x1b[36m\1\\x1b[m:\2/' | column -c2 -t -s :)"

.PHONY: clean-img
clean-img: ## Remove autogenerated image files
	rm -rf public/
	find static -name "*.avif" -delete
	find static -name "*.webp" -delete

.PHONY: clean-pub
clean-pub: ## Remove build files
	rm -rf public/

.PHONY: clean
clean: clean-pub clean-img ## Remove public files and images

.PHONY: versions
versions: ## Show versions of tools
	zola --version
	gh-stats --version
	tinysearch --version
	wasm-opt --version
	terser --version
	cavif --version
	convert -version

.PHONY: content
content: ## Build the content of the static site with zola
	zola build

.PHONY: images
images: ## Create avif images 
	cargo run --manifest-path ./helpers/img/Cargo.toml

# Keep a copy in static/ so plain `zola serve` can load search locally.
# Production still gets a freshly generated copy in public/.
.PHONY: index
index: content ## Build the search index with tinysearch
	@tinysearch --version | grep -q "tinysearch $(TINYSEARCH_VERSION)" || (echo "tinysearch $(TINYSEARCH_VERSION) is required"; exit 1)
	tinysearch --release -o -m wasm -p static public/search_index.en.json
	cp static/tinysearch_engine.wasm public/
	rm public/search_index.en.json

.PHONY: minify
minify: index ## Compress JavaScript assets
	terser --module --compress --mangle --output public/search.mjs -- static/search.mjs

.PHONY: build 
build: stars minify ## Build static site and search index, minify JS

.PHONY: build-quick
build-quick: content ## Build static site

.PHONY: dev run serve
dev run serve: ## Serve website locally
	zola serve --fast

.PHONY: stars
stars: ## Update Github stars statistics for my projects
	gh-stats --filter gitpod --stars 100 --template .star-counter-template.md --output content/static/about/stars.md
